// AUTO-GENERATED (partial) - do not edit y_/n_/i_ sections by hand.
// Corpus generated by tools/gen_jsontestsuite_inline.py from JSONTestSuite/test_parsing
// Hand-written behavioral tests are appended below the corpus.
//
// JSONTestSuite conformance results baked in:
//   y_ (MUST accept) : 95/95
//   n_ (MUST reject) : 188/188
//   i_ accepted      : 30
//   i_ rejected      : 5

#include <gtest/gtest.h>
#include "../src/zjson.hpp"
#include <string>

using ZJSON::Json;

// Helper: parse with strict RFC mode
static bool zjson_accepts(const std::string& input) {
    std::string err;
    Json j = Json::ParseJsonStrict(input, err);
    return !j.isError();
}

static std::string repeat_concat(const std::string& pattern, size_t count,
                                 const std::string& tail = std::string()) {
    std::string out;
    out.reserve(pattern.size() * count + tail.size());
    for (size_t index = 0; index < count; ++index) out += pattern;
    out += tail;
    return out;
}

// ============================================================
// y_: MUST accept - RFC 8259 valid documents
// ============================================================
TEST(JSONTestSuite_y, MustAccept_0) {
    // y_array_arraysWithSpaces
    EXPECT_TRUE(zjson_accepts(std::string("[[]   ]", 7))) << "Should accept: y_array_arraysWithSpaces";
    // y_array_empty-string
    EXPECT_TRUE(zjson_accepts(std::string("[\"\"]", 4))) << "Should accept: y_array_empty-string";
    // y_array_empty
    EXPECT_TRUE(zjson_accepts(std::string("[]", 2))) << "Should accept: y_array_empty";
    // y_array_ending_with_newline
    EXPECT_TRUE(zjson_accepts(std::string("[\"a\"]", 5))) << "Should accept: y_array_ending_with_newline";
    // y_array_false
    EXPECT_TRUE(zjson_accepts(std::string("[false]", 7))) << "Should accept: y_array_false";
    // y_array_heterogeneous
    EXPECT_TRUE(zjson_accepts(std::string("[null, 1, \"1\", {}]", 18))) << "Should accept: y_array_heterogeneous";
    // y_array_null
    EXPECT_TRUE(zjson_accepts(std::string("[null]", 6))) << "Should accept: y_array_null";
    // y_array_with_1_and_newline
    EXPECT_TRUE(zjson_accepts(std::string("[1\n]", 4))) << "Should accept: y_array_with_1_and_newline";
    // y_array_with_leading_space
    EXPECT_TRUE(zjson_accepts(std::string(" [1]", 4))) << "Should accept: y_array_with_leading_space";
    // y_array_with_several_null
    EXPECT_TRUE(zjson_accepts(std::string("[1,null,null,null,2]", 20))) << "Should accept: y_array_with_several_null";
    // y_array_with_trailing_space
    EXPECT_TRUE(zjson_accepts(std::string("[2] ", 4))) << "Should accept: y_array_with_trailing_space";
    // y_number
    EXPECT_TRUE(zjson_accepts(std::string("[123e65]", 8))) << "Should accept: y_number";
    // y_number_0e+1
    EXPECT_TRUE(zjson_accepts(std::string("[0e+1]", 6))) << "Should accept: y_number_0e+1";
    // y_number_0e1
    EXPECT_TRUE(zjson_accepts(std::string("[0e1]", 5))) << "Should accept: y_number_0e1";
    // y_number_after_space
    EXPECT_TRUE(zjson_accepts(std::string("[ 4]", 4))) << "Should accept: y_number_after_space";
    // y_number_double_close_to_zero
    EXPECT_TRUE(zjson_accepts(std::string("[-0.000000000000000000000000000000000000000000000000000000000000000000000000000001]\n", 84))) << "Should accept: y_number_double_close_to_zero";
    // y_number_int_with_exp
    EXPECT_TRUE(zjson_accepts(std::string("[20e1]", 6))) << "Should accept: y_number_int_with_exp";
    // y_number_minus_zero
    EXPECT_TRUE(zjson_accepts(std::string("[-0]", 4))) << "Should accept: y_number_minus_zero";
    // y_number_negative_int
    EXPECT_TRUE(zjson_accepts(std::string("[-123]", 6))) << "Should accept: y_number_negative_int";
    // y_number_negative_one
    EXPECT_TRUE(zjson_accepts(std::string("[-1]", 4))) << "Should accept: y_number_negative_one";
    // y_number_negative_zero
    EXPECT_TRUE(zjson_accepts(std::string("[-0]", 4))) << "Should accept: y_number_negative_zero";
    // y_number_real_capital_e
    EXPECT_TRUE(zjson_accepts(std::string("[1E22]", 6))) << "Should accept: y_number_real_capital_e";
    // y_number_real_capital_e_neg_exp
    EXPECT_TRUE(zjson_accepts(std::string("[1E-2]", 6))) << "Should accept: y_number_real_capital_e_neg_exp";
    // y_number_real_capital_e_pos_exp
    EXPECT_TRUE(zjson_accepts(std::string("[1E+2]", 6))) << "Should accept: y_number_real_capital_e_pos_exp";
    // y_number_real_exponent
    EXPECT_TRUE(zjson_accepts(std::string("[123e45]", 8))) << "Should accept: y_number_real_exponent";
}

TEST(JSONTestSuite_y, MustAccept_1) {
    // y_number_real_fraction_exponent
    EXPECT_TRUE(zjson_accepts(std::string("[123.456e78]", 12))) << "Should accept: y_number_real_fraction_exponent";
    // y_number_real_neg_exp
    EXPECT_TRUE(zjson_accepts(std::string("[1e-2]", 6))) << "Should accept: y_number_real_neg_exp";
    // y_number_real_pos_exponent
    EXPECT_TRUE(zjson_accepts(std::string("[1e+2]", 6))) << "Should accept: y_number_real_pos_exponent";
    // y_number_simple_int
    EXPECT_TRUE(zjson_accepts(std::string("[123]", 5))) << "Should accept: y_number_simple_int";
    // y_number_simple_real
    EXPECT_TRUE(zjson_accepts(std::string("[123.456789]", 12))) << "Should accept: y_number_simple_real";
    // y_object
    EXPECT_TRUE(zjson_accepts(std::string("{\"asd\":\"sdf\", \"dfg\":\"fgh\"}", 26))) << "Should accept: y_object";
    // y_object_basic
    EXPECT_TRUE(zjson_accepts(std::string("{\"asd\":\"sdf\"}", 13))) << "Should accept: y_object_basic";
    // y_object_duplicated_key
    EXPECT_TRUE(zjson_accepts(std::string("{\"a\":\"b\",\"a\":\"c\"}", 17))) << "Should accept: y_object_duplicated_key";
    // y_object_duplicated_key_and_value
    EXPECT_TRUE(zjson_accepts(std::string("{\"a\":\"b\",\"a\":\"b\"}", 17))) << "Should accept: y_object_duplicated_key_and_value";
    // y_object_empty
    EXPECT_TRUE(zjson_accepts(std::string("{}", 2))) << "Should accept: y_object_empty";
    // y_object_empty_key
    EXPECT_TRUE(zjson_accepts(std::string("{\"\":0}", 6))) << "Should accept: y_object_empty_key";
    // y_object_escaped_null_in_key
    EXPECT_TRUE(zjson_accepts(std::string("{\"foo\\u0000bar\": 42}", 20))) << "Should accept: y_object_escaped_null_in_key";
    // y_object_extreme_numbers
    EXPECT_TRUE(zjson_accepts(std::string("{ \"min\": -1.0e+28, \"max\": 1.0e+28 }", 35))) << "Should accept: y_object_extreme_numbers";
    // y_object_long_strings
    EXPECT_TRUE(zjson_accepts(std::string("{\"x\":[{\"id\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}], \"id\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}", 108))) << "Should accept: y_object_long_strings";
    // y_object_simple
    EXPECT_TRUE(zjson_accepts(std::string("{\"a\":[]}", 8))) << "Should accept: y_object_simple";
    // y_object_string_unicode
    EXPECT_TRUE(zjson_accepts(std::string("{\"title\":\"\\u041f\\u043e\\u043b\\u0442\\u043e\\u0440\\u0430 \\u0417\\u0435\\u043c\\u043b\\u0435\\u043a\\u043e\\u043f\\u0430\" }", 110))) << "Should accept: y_object_string_unicode";
    // y_object_with_newlines
    EXPECT_TRUE(zjson_accepts(std::string("{\n\"a\": \"b\"\n}", 12))) << "Should accept: y_object_with_newlines";
    // y_string_1_2_3_bytes_UTF-8_sequences
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\u0060\\u012a\\u12AB\"]", 22))) << "Should accept: y_string_1_2_3_bytes_UTF-8_sequences";
    // y_string_accepted_surrogate_pair
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uD801\\udc37\"]", 16))) << "Should accept: y_string_accepted_surrogate_pair";
    // y_string_accepted_surrogate_pairs
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\ud83d\\ude39\\ud83d\\udc8d\"]", 28))) << "Should accept: y_string_accepted_surrogate_pairs";
    // y_string_allowed_escapes
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\\"\\\\\\/\\b\\f\\n\\r\\t\"]", 20))) << "Should accept: y_string_allowed_escapes";
    // y_string_backslash_and_u_escaped_zero
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\\\u0000\"]", 11))) << "Should accept: y_string_backslash_and_u_escaped_zero";
    // y_string_backslash_doublequotes
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\\"\"]", 6))) << "Should accept: y_string_backslash_doublequotes";
    // y_string_comments
    EXPECT_TRUE(zjson_accepts(std::string("[\"a/*b*/c/*d//e\"]", 17))) << "Should accept: y_string_comments";
    // y_string_double_escape_a
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\\\a\"]", 7))) << "Should accept: y_string_double_escape_a";
}

TEST(JSONTestSuite_y, MustAccept_2) {
    // y_string_double_escape_n
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\\\n\"]", 7))) << "Should accept: y_string_double_escape_n";
    // y_string_escaped_control_character
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\u0012\"]", 10))) << "Should accept: y_string_escaped_control_character";
    // y_string_escaped_noncharacter
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uFFFF\"]", 10))) << "Should accept: y_string_escaped_noncharacter";
    // y_string_in_array
    EXPECT_TRUE(zjson_accepts(std::string("[\"asd\"]", 7))) << "Should accept: y_string_in_array";
    // y_string_in_array_with_leading_space
    EXPECT_TRUE(zjson_accepts(std::string("[ \"asd\"]", 8))) << "Should accept: y_string_in_array_with_leading_space";
    // y_string_last_surrogates_1_and_2
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uDBFF\\uDFFF\"]", 16))) << "Should accept: y_string_last_surrogates_1_and_2";
    // y_string_nbsp_uescaped
    EXPECT_TRUE(zjson_accepts(std::string("[\"new\\u00A0line\"]", 17))) << "Should accept: y_string_nbsp_uescaped";
    // y_string_nonCharacterInUTF-8_U+10FFFF
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xf4\x8f\xbf\xbf\"]", 8))) << "Should accept: y_string_nonCharacterInUTF-8_U+10FFFF";
    // y_string_nonCharacterInUTF-8_U+FFFF
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xef\xbf\xbf\"]", 7))) << "Should accept: y_string_nonCharacterInUTF-8_U+FFFF";
    // y_string_null_escape
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\u0000\"]", 10))) << "Should accept: y_string_null_escape";
    // y_string_one-byte-utf-8
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\u002c\"]", 10))) << "Should accept: y_string_one-byte-utf-8";
    // y_string_pi
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xcf\x80\"]", 6))) << "Should accept: y_string_pi";
    // y_string_reservedCharacterInUTF-8_U+1BFFF
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xf0\x9b\xbf\xbf\"]", 8))) << "Should accept: y_string_reservedCharacterInUTF-8_U+1BFFF";
    // y_string_simple_ascii
    EXPECT_TRUE(zjson_accepts(std::string("[\"asd \"]", 8))) << "Should accept: y_string_simple_ascii";
    // y_string_space
    EXPECT_TRUE(zjson_accepts(std::string("\" \"", 3))) << "Should accept: y_string_space";
    // y_string_surrogates_U+1D11E_MUSICAL_SYMBOL_G_CLEF
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uD834\\uDd1e\"]", 16))) << "Should accept: y_string_surrogates_U+1D11E_MUSICAL_SYMBOL_G_CLEF";
    // y_string_three-byte-utf-8
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\u0821\"]", 10))) << "Should accept: y_string_three-byte-utf-8";
    // y_string_two-byte-utf-8
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\u0123\"]", 10))) << "Should accept: y_string_two-byte-utf-8";
    // y_string_u+2028_line_sep
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xe2\x80\xa8\"]", 7))) << "Should accept: y_string_u+2028_line_sep";
    // y_string_u+2029_par_sep
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xe2\x80\xa9\"]", 7))) << "Should accept: y_string_u+2029_par_sep";
    // y_string_uEscape
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\u0061\\u30af\\u30EA\\u30b9\"]", 28))) << "Should accept: y_string_uEscape";
    // y_string_uescaped_newline
    EXPECT_TRUE(zjson_accepts(std::string("[\"new\\u000Aline\"]", 17))) << "Should accept: y_string_uescaped_newline";
    // y_string_unescaped_char_delete
    EXPECT_TRUE(zjson_accepts(std::string("[\"\x7f\"]", 5))) << "Should accept: y_string_unescaped_char_delete";
    // y_string_unicode
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uA66D\"]", 10))) << "Should accept: y_string_unicode";
    // y_string_unicodeEscapedBackslash
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\u005C\"]", 10))) << "Should accept: y_string_unicodeEscapedBackslash";
}

TEST(JSONTestSuite_y, MustAccept_3) {
    // y_string_unicode_2
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xe2\x8d\x82\xe3\x88\xb4\xe2\x8d\x82\"]", 13))) << "Should accept: y_string_unicode_2";
    // y_string_unicode_U+10FFFE_nonchar
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uDBFF\\uDFFE\"]", 16))) << "Should accept: y_string_unicode_U+10FFFE_nonchar";
    // y_string_unicode_U+1FFFE_nonchar
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uD83F\\uDFFE\"]", 16))) << "Should accept: y_string_unicode_U+1FFFE_nonchar";
    // y_string_unicode_U+200B_ZERO_WIDTH_SPACE
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\u200B\"]", 10))) << "Should accept: y_string_unicode_U+200B_ZERO_WIDTH_SPACE";
    // y_string_unicode_U+2064_invisible_plus
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\u2064\"]", 10))) << "Should accept: y_string_unicode_U+2064_invisible_plus";
    // y_string_unicode_U+FDD0_nonchar
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uFDD0\"]", 10))) << "Should accept: y_string_unicode_U+FDD0_nonchar";
    // y_string_unicode_U+FFFE_nonchar
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uFFFE\"]", 10))) << "Should accept: y_string_unicode_U+FFFE_nonchar";
    // y_string_unicode_escaped_double_quote
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\u0022\"]", 10))) << "Should accept: y_string_unicode_escaped_double_quote";
    // y_string_utf8
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xe2\x82\xac\xf0\x9d\x84\x9e\"]", 11))) << "Should accept: y_string_utf8";
    // y_string_with_del_character
    EXPECT_TRUE(zjson_accepts(std::string("[\"a\x7f" "a\"]", 7))) << "Should accept: y_string_with_del_character";
    // y_structure_lonely_false
    EXPECT_TRUE(zjson_accepts(std::string("false", 5))) << "Should accept: y_structure_lonely_false";
    // y_structure_lonely_int
    EXPECT_TRUE(zjson_accepts(std::string("42", 2))) << "Should accept: y_structure_lonely_int";
    // y_structure_lonely_negative_real
    EXPECT_TRUE(zjson_accepts(std::string("-0.1", 4))) << "Should accept: y_structure_lonely_negative_real";
    // y_structure_lonely_null
    EXPECT_TRUE(zjson_accepts(std::string("null", 4))) << "Should accept: y_structure_lonely_null";
    // y_structure_lonely_string
    EXPECT_TRUE(zjson_accepts(std::string("\"asd\"", 5))) << "Should accept: y_structure_lonely_string";
    // y_structure_lonely_true
    EXPECT_TRUE(zjson_accepts(std::string("true", 4))) << "Should accept: y_structure_lonely_true";
    // y_structure_string_empty
    EXPECT_TRUE(zjson_accepts(std::string(2, '"'))) << "Should accept: y_structure_string_empty";
    // y_structure_trailing_newline
    EXPECT_TRUE(zjson_accepts(std::string("[\"a\"]\n", 6))) << "Should accept: y_structure_trailing_newline";
    // y_structure_true_in_array
    EXPECT_TRUE(zjson_accepts(std::string("[true]", 6))) << "Should accept: y_structure_true_in_array";
    // y_structure_whitespace_array
    EXPECT_TRUE(zjson_accepts(std::string(" [] ", 4))) << "Should accept: y_structure_whitespace_array";
}

// ============================================================
// n_: MUST reject - RFC 8259 invalid documents
// ============================================================
TEST(JSONTestSuite_n, MustReject_0) {
    // n_array_1_true_without_comma
    EXPECT_FALSE(zjson_accepts(std::string("[1 true]", 8))) << "Should reject: n_array_1_true_without_comma";
    // n_array_a_invalid_utf8
    EXPECT_FALSE(zjson_accepts(std::string("[a\xe5]", 4))) << "Should reject: n_array_a_invalid_utf8";
    // n_array_colon_instead_of_comma
    EXPECT_FALSE(zjson_accepts(std::string("[\"\": 1]", 7))) << "Should reject: n_array_colon_instead_of_comma";
    // n_array_comma_after_close
    EXPECT_FALSE(zjson_accepts(std::string("[\"\"],", 5))) << "Should reject: n_array_comma_after_close";
    // n_array_comma_and_number
    EXPECT_FALSE(zjson_accepts(std::string("[,1]", 4))) << "Should reject: n_array_comma_and_number";
    // n_array_double_comma
    EXPECT_FALSE(zjson_accepts(std::string("[1,,2]", 6))) << "Should reject: n_array_double_comma";
    // n_array_double_extra_comma
    EXPECT_FALSE(zjson_accepts(std::string("[\"x\",,]", 7))) << "Should reject: n_array_double_extra_comma";
    // n_array_extra_close
    EXPECT_FALSE(zjson_accepts(std::string("[\"x\"]]", 6))) << "Should reject: n_array_extra_close";
    // n_array_extra_comma
    EXPECT_FALSE(zjson_accepts(std::string("[\"\",]", 5))) << "Should reject: n_array_extra_comma";
    // n_array_incomplete
    EXPECT_FALSE(zjson_accepts(std::string("[\"x\"", 4))) << "Should reject: n_array_incomplete";
    // n_array_incomplete_invalid_value
    EXPECT_FALSE(zjson_accepts(std::string("[x", 2))) << "Should reject: n_array_incomplete_invalid_value";
    // n_array_inner_array_no_comma
    EXPECT_FALSE(zjson_accepts(std::string("[3[4]]", 6))) << "Should reject: n_array_inner_array_no_comma";
    // n_array_invalid_utf8
    EXPECT_FALSE(zjson_accepts(std::string("[\xff]", 3))) << "Should reject: n_array_invalid_utf8";
    // n_array_items_separated_by_semicolon
    EXPECT_FALSE(zjson_accepts(std::string("[1:2]", 5))) << "Should reject: n_array_items_separated_by_semicolon";
    // n_array_just_comma
    EXPECT_FALSE(zjson_accepts(std::string("[,]", 3))) << "Should reject: n_array_just_comma";
    // n_array_just_minus
    EXPECT_FALSE(zjson_accepts(std::string("[-]", 3))) << "Should reject: n_array_just_minus";
    // n_array_missing_value
    EXPECT_FALSE(zjson_accepts(std::string("[   , \"\"]", 9))) << "Should reject: n_array_missing_value";
    // n_array_newlines_unclosed
    EXPECT_FALSE(zjson_accepts(std::string("[\"a\",\n4\n,1,", 11))) << "Should reject: n_array_newlines_unclosed";
    // n_array_number_and_comma
    EXPECT_FALSE(zjson_accepts(std::string("[1,]", 4))) << "Should reject: n_array_number_and_comma";
    // n_array_number_and_several_commas
    EXPECT_FALSE(zjson_accepts(std::string("[1,,]", 5))) << "Should reject: n_array_number_and_several_commas";
    // n_array_spaces_vertical_tab_formfeed
    EXPECT_FALSE(zjson_accepts(std::string("[\"\x0b" "a\"\\f]", 8))) << "Should reject: n_array_spaces_vertical_tab_formfeed";
    // n_array_star_inside
    EXPECT_FALSE(zjson_accepts(std::string("[*]", 3))) << "Should reject: n_array_star_inside";
    // n_array_unclosed
    EXPECT_FALSE(zjson_accepts(std::string("[\"\"", 3))) << "Should reject: n_array_unclosed";
    // n_array_unclosed_trailing_comma
    EXPECT_FALSE(zjson_accepts(std::string("[1,", 3))) << "Should reject: n_array_unclosed_trailing_comma";
    // n_array_unclosed_with_new_lines
    EXPECT_FALSE(zjson_accepts(std::string("[1,\n1\n,1", 8))) << "Should reject: n_array_unclosed_with_new_lines";
}

TEST(JSONTestSuite_n, MustReject_1) {
    // n_array_unclosed_with_object_inside
    EXPECT_FALSE(zjson_accepts(std::string("[{}", 3))) << "Should reject: n_array_unclosed_with_object_inside";
    // n_incomplete_false
    EXPECT_FALSE(zjson_accepts(std::string("[fals]", 6))) << "Should reject: n_incomplete_false";
    // n_incomplete_null
    EXPECT_FALSE(zjson_accepts(std::string("[nul]", 5))) << "Should reject: n_incomplete_null";
    // n_incomplete_true
    EXPECT_FALSE(zjson_accepts(std::string("[tru]", 5))) << "Should reject: n_incomplete_true";
    // n_multidigit_number_then_00
    EXPECT_FALSE(zjson_accepts(std::string("123\x00", 4))) << "Should reject: n_multidigit_number_then_00";
    // n_number_++
    EXPECT_FALSE(zjson_accepts(std::string("[++1234]", 8))) << "Should reject: n_number_++";
    // n_number_+1
    EXPECT_FALSE(zjson_accepts(std::string("[+1]", 4))) << "Should reject: n_number_+1";
    // n_number_+Inf
    EXPECT_FALSE(zjson_accepts(std::string("[+Inf]", 6))) << "Should reject: n_number_+Inf";
    // n_number_-01
    EXPECT_FALSE(zjson_accepts(std::string("[-01]", 5))) << "Should reject: n_number_-01";
    // n_number_-1.0.
    EXPECT_FALSE(zjson_accepts(std::string("[-1.0.]", 7))) << "Should reject: n_number_-1.0.";
    // n_number_-2.
    EXPECT_FALSE(zjson_accepts(std::string("[-2.]", 5))) << "Should reject: n_number_-2.";
    // n_number_-NaN
    EXPECT_FALSE(zjson_accepts(std::string("[-NaN]", 6))) << "Should reject: n_number_-NaN";
    // n_number_.-1
    EXPECT_FALSE(zjson_accepts(std::string("[.-1]", 5))) << "Should reject: n_number_.-1";
    // n_number_.2e-3
    EXPECT_FALSE(zjson_accepts(std::string("[.2e-3]", 7))) << "Should reject: n_number_.2e-3";
    // n_number_0.1.2
    EXPECT_FALSE(zjson_accepts(std::string("[0.1.2]", 7))) << "Should reject: n_number_0.1.2";
    // n_number_0.3e+
    EXPECT_FALSE(zjson_accepts(std::string("[0.3e+]", 7))) << "Should reject: n_number_0.3e+";
    // n_number_0.3e
    EXPECT_FALSE(zjson_accepts(std::string("[0.3e]", 6))) << "Should reject: n_number_0.3e";
    // n_number_0.e1
    EXPECT_FALSE(zjson_accepts(std::string("[0.e1]", 6))) << "Should reject: n_number_0.e1";
    // n_number_0_capital_E+
    EXPECT_FALSE(zjson_accepts(std::string("[0E+]", 5))) << "Should reject: n_number_0_capital_E+";
    // n_number_0_capital_E
    EXPECT_FALSE(zjson_accepts(std::string("[0E]", 4))) << "Should reject: n_number_0_capital_E";
    // n_number_0e+
    EXPECT_FALSE(zjson_accepts(std::string("[0e+]", 5))) << "Should reject: n_number_0e+";
    // n_number_0e
    EXPECT_FALSE(zjson_accepts(std::string("[0e]", 4))) << "Should reject: n_number_0e";
    // n_number_1.0e+
    EXPECT_FALSE(zjson_accepts(std::string("[1.0e+]", 7))) << "Should reject: n_number_1.0e+";
    // n_number_1.0e-
    EXPECT_FALSE(zjson_accepts(std::string("[1.0e-]", 7))) << "Should reject: n_number_1.0e-";
    // n_number_1.0e
    EXPECT_FALSE(zjson_accepts(std::string("[1.0e]", 6))) << "Should reject: n_number_1.0e";
}

TEST(JSONTestSuite_n, MustReject_2) {
    // n_number_1_000
    EXPECT_FALSE(zjson_accepts(std::string("[1 000.0]", 9))) << "Should reject: n_number_1_000";
    // n_number_1eE2
    EXPECT_FALSE(zjson_accepts(std::string("[1eE2]", 6))) << "Should reject: n_number_1eE2";
    // n_number_2.e+3
    EXPECT_FALSE(zjson_accepts(std::string("[2.e+3]", 7))) << "Should reject: n_number_2.e+3";
    // n_number_2.e-3
    EXPECT_FALSE(zjson_accepts(std::string("[2.e-3]", 7))) << "Should reject: n_number_2.e-3";
    // n_number_2.e3
    EXPECT_FALSE(zjson_accepts(std::string("[2.e3]", 6))) << "Should reject: n_number_2.e3";
    // n_number_9.e+
    EXPECT_FALSE(zjson_accepts(std::string("[9.e+]", 6))) << "Should reject: n_number_9.e+";
    // n_number_Inf
    EXPECT_FALSE(zjson_accepts(std::string("[Inf]", 5))) << "Should reject: n_number_Inf";
    // n_number_NaN
    EXPECT_FALSE(zjson_accepts(std::string("[NaN]", 5))) << "Should reject: n_number_NaN";
    // n_number_U+FF11_fullwidth_digit_one
    EXPECT_FALSE(zjson_accepts(std::string("[\xef\xbc\x91]", 5))) << "Should reject: n_number_U+FF11_fullwidth_digit_one";
    // n_number_expression
    EXPECT_FALSE(zjson_accepts(std::string("[1+2]", 5))) << "Should reject: n_number_expression";
    // n_number_hex_1_digit
    EXPECT_FALSE(zjson_accepts(std::string("[0x1]", 5))) << "Should reject: n_number_hex_1_digit";
    // n_number_hex_2_digits
    EXPECT_FALSE(zjson_accepts(std::string("[0x42]", 6))) << "Should reject: n_number_hex_2_digits";
    // n_number_infinity
    EXPECT_FALSE(zjson_accepts(std::string("[Infinity]", 10))) << "Should reject: n_number_infinity";
    // n_number_invalid+-
    EXPECT_FALSE(zjson_accepts(std::string("[0e+-1]", 7))) << "Should reject: n_number_invalid+-";
    // n_number_invalid-negative-real
    EXPECT_FALSE(zjson_accepts(std::string("[-123.123foo]", 13))) << "Should reject: n_number_invalid-negative-real";
    // n_number_invalid-utf-8-in-bigger-int
    EXPECT_FALSE(zjson_accepts(std::string("[123\xe5]", 6))) << "Should reject: n_number_invalid-utf-8-in-bigger-int";
    // n_number_invalid-utf-8-in-exponent
    EXPECT_FALSE(zjson_accepts(std::string("[1e1\xe5]", 6))) << "Should reject: n_number_invalid-utf-8-in-exponent";
    // n_number_invalid-utf-8-in-int
    EXPECT_FALSE(zjson_accepts(std::string("[0\xe5]\n", 5))) << "Should reject: n_number_invalid-utf-8-in-int";
    // n_number_minus_infinity
    EXPECT_FALSE(zjson_accepts(std::string("[-Infinity]", 11))) << "Should reject: n_number_minus_infinity";
    // n_number_minus_sign_with_trailing_garbage
    EXPECT_FALSE(zjson_accepts(std::string("[-foo]", 6))) << "Should reject: n_number_minus_sign_with_trailing_garbage";
    // n_number_minus_space_1
    EXPECT_FALSE(zjson_accepts(std::string("[- 1]", 5))) << "Should reject: n_number_minus_space_1";
    // n_number_neg_int_starting_with_zero
    EXPECT_FALSE(zjson_accepts(std::string("[-012]", 6))) << "Should reject: n_number_neg_int_starting_with_zero";
    // n_number_neg_real_without_int_part
    EXPECT_FALSE(zjson_accepts(std::string("[-.123]", 7))) << "Should reject: n_number_neg_real_without_int_part";
    // n_number_neg_with_garbage_at_end
    EXPECT_FALSE(zjson_accepts(std::string("[-1x]", 5))) << "Should reject: n_number_neg_with_garbage_at_end";
    // n_number_real_garbage_after_e
    EXPECT_FALSE(zjson_accepts(std::string("[1ea]", 5))) << "Should reject: n_number_real_garbage_after_e";
}

TEST(JSONTestSuite_n, MustReject_3) {
    // n_number_real_with_invalid_utf8_after_e
    EXPECT_FALSE(zjson_accepts(std::string("[1e\xe5]", 5))) << "Should reject: n_number_real_with_invalid_utf8_after_e";
    // n_number_real_without_fractional_part
    EXPECT_FALSE(zjson_accepts(std::string("[1.]", 4))) << "Should reject: n_number_real_without_fractional_part";
    // n_number_starting_with_dot
    EXPECT_FALSE(zjson_accepts(std::string("[.123]", 6))) << "Should reject: n_number_starting_with_dot";
    // n_number_with_alpha
    EXPECT_FALSE(zjson_accepts(std::string("[1.2a-3]", 8))) << "Should reject: n_number_with_alpha";
    // n_number_with_alpha_char
    EXPECT_FALSE(zjson_accepts(std::string("[1.8011670033376514H-308]", 25))) << "Should reject: n_number_with_alpha_char";
    // n_number_with_leading_zero
    EXPECT_FALSE(zjson_accepts(std::string("[012]", 5))) << "Should reject: n_number_with_leading_zero";
    // n_object_bad_value
    EXPECT_FALSE(zjson_accepts(std::string("[\"x\", truth]", 12))) << "Should reject: n_object_bad_value";
    // n_object_bracket_key
    EXPECT_FALSE(zjson_accepts(std::string("{[: \"x\"}\n", 9))) << "Should reject: n_object_bracket_key";
    // n_object_comma_instead_of_colon
    EXPECT_FALSE(zjson_accepts(std::string("{\"x\", null}", 11))) << "Should reject: n_object_comma_instead_of_colon";
    // n_object_double_colon
    EXPECT_FALSE(zjson_accepts(std::string("{\"x\"::\"b\"}", 10))) << "Should reject: n_object_double_colon";
    // n_object_emoji
    EXPECT_FALSE(zjson_accepts(std::string("{\xf0\x9f\x87\xa8\xf0\x9f\x87\xad}", 10))) << "Should reject: n_object_emoji";
    // n_object_garbage_at_end
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\":\"a\" 123}", 13))) << "Should reject: n_object_garbage_at_end";
    // n_object_key_with_single_quotes
    EXPECT_FALSE(zjson_accepts(std::string("{key: 'value'}", 14))) << "Should reject: n_object_key_with_single_quotes";
    // n_object_lone_continuation_byte_in_key_and_trailing_comma
    EXPECT_FALSE(zjson_accepts(std::string("{\"\xb9\":\"0\",}", 10))) << "Should reject: n_object_lone_continuation_byte_in_key_and_trailing_comma";
    // n_object_missing_colon
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\" b}", 7))) << "Should reject: n_object_missing_colon";
    // n_object_missing_key
    EXPECT_FALSE(zjson_accepts(std::string("{:\"b\"}", 6))) << "Should reject: n_object_missing_key";
    // n_object_missing_semicolon
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\" \"b\"}", 9))) << "Should reject: n_object_missing_semicolon";
    // n_object_missing_value
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\":", 5))) << "Should reject: n_object_missing_value";
    // n_object_no-colon
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\"", 4))) << "Should reject: n_object_no-colon";
    // n_object_non_string_key
    EXPECT_FALSE(zjson_accepts(std::string("{1:1}", 5))) << "Should reject: n_object_non_string_key";
    // n_object_non_string_key_but_huge_number_instead
    EXPECT_FALSE(zjson_accepts(std::string("{9999E9999:1}", 13))) << "Should reject: n_object_non_string_key_but_huge_number_instead";
    // n_object_repeated_null_null
    EXPECT_FALSE(zjson_accepts(std::string("{null:null,null:null}", 21))) << "Should reject: n_object_repeated_null_null";
    // n_object_several_trailing_commas
    EXPECT_FALSE(zjson_accepts(std::string("{\"id\":0,,,,,}", 13))) << "Should reject: n_object_several_trailing_commas";
    // n_object_single_quote
    EXPECT_FALSE(zjson_accepts(std::string("{'a':0}", 7))) << "Should reject: n_object_single_quote";
    // n_object_trailing_comma
    EXPECT_FALSE(zjson_accepts(std::string("{\"id\":0,}", 9))) << "Should reject: n_object_trailing_comma";
}

TEST(JSONTestSuite_n, MustReject_4) {
    // n_object_trailing_comment
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\":\"b\"}/**/", 13))) << "Should reject: n_object_trailing_comment";
    // n_object_trailing_comment_open
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\":\"b\"}/**//", 14))) << "Should reject: n_object_trailing_comment_open";
    // n_object_trailing_comment_slash_open
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\":\"b\"}//", 11))) << "Should reject: n_object_trailing_comment_slash_open";
    // n_object_trailing_comment_slash_open_incomplete
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\":\"b\"}/", 10))) << "Should reject: n_object_trailing_comment_slash_open_incomplete";
    // n_object_two_commas_in_a_row
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\":\"b\",,\"c\":\"d\"}", 18))) << "Should reject: n_object_two_commas_in_a_row";
    // n_object_unquoted_key
    EXPECT_FALSE(zjson_accepts(std::string("{a: \"b\"}", 8))) << "Should reject: n_object_unquoted_key";
    // n_object_unterminated-value
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\":\"a", 7))) << "Should reject: n_object_unterminated-value";
    // n_object_with_single_string
    EXPECT_FALSE(zjson_accepts(std::string("{ \"foo\" : \"bar\", \"a\" }", 22))) << "Should reject: n_object_with_single_string";
    // n_object_with_trailing_garbage
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\":\"b\"}#", 10))) << "Should reject: n_object_with_trailing_garbage";
    // n_single_space
    EXPECT_FALSE(zjson_accepts(std::string(1, ' '))) << "Should reject: n_single_space";
    // n_string_1_surrogate_then_escape
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\uD800\\\"]", 11))) << "Should reject: n_string_1_surrogate_then_escape";
    // n_string_1_surrogate_then_escape_u
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\uD800\\u\"]", 12))) << "Should reject: n_string_1_surrogate_then_escape_u";
    // n_string_1_surrogate_then_escape_u1
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\uD800\\u1\"]", 13))) << "Should reject: n_string_1_surrogate_then_escape_u1";
    // n_string_1_surrogate_then_escape_u1x
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\uD800\\u1x\"]", 14))) << "Should reject: n_string_1_surrogate_then_escape_u1x";
    // n_string_accentuated_char_no_quotes
    EXPECT_FALSE(zjson_accepts(std::string("[\xc3\xa9]", 4))) << "Should reject: n_string_accentuated_char_no_quotes";
    // n_string_backslash_00
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\\x00\"]", 6))) << "Should reject: n_string_backslash_00";
    // n_string_escape_x
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\x00\"]", 8))) << "Should reject: n_string_escape_x";
    // n_string_escaped_backslash_bad
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\\\\\\"]", 7))) << "Should reject: n_string_escaped_backslash_bad";
    // n_string_escaped_ctrl_char_tab
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\\t\"]", 6))) << "Should reject: n_string_escaped_ctrl_char_tab";
    // n_string_escaped_emoji
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\\xf0\x9f\x8c\x80\"]", 9))) << "Should reject: n_string_escaped_emoji";
    // n_string_incomplete_escape
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\\"]", 5))) << "Should reject: n_string_incomplete_escape";
    // n_string_incomplete_escaped_character
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\u00A\"]", 9))) << "Should reject: n_string_incomplete_escaped_character";
    // n_string_incomplete_surrogate
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\uD834\\uDd\"]", 14))) << "Should reject: n_string_incomplete_surrogate";
    // n_string_incomplete_surrogate_escape_invalid
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\uD800\\uD800\\x\"]", 18))) << "Should reject: n_string_incomplete_surrogate_escape_invalid";
    // n_string_invalid-utf-8-in-escape
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\u\xe5\"]", 7))) << "Should reject: n_string_invalid-utf-8-in-escape";
}

TEST(JSONTestSuite_n, MustReject_5) {
    // n_string_invalid_backslash_esc
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\a\"]", 6))) << "Should reject: n_string_invalid_backslash_esc";
    // n_string_invalid_unicode_escape
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\uqqqq\"]", 10))) << "Should reject: n_string_invalid_unicode_escape";
    // n_string_invalid_utf8_after_escape
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\\xe5\"]", 6))) << "Should reject: n_string_invalid_utf8_after_escape";
    // n_string_leading_uescaped_thinspace
    EXPECT_FALSE(zjson_accepts(std::string("[\\u0020\"asd\"]", 13))) << "Should reject: n_string_leading_uescaped_thinspace";
    // n_string_no_quotes_with_bad_escape
    EXPECT_FALSE(zjson_accepts(std::string("[\\n]", 4))) << "Should reject: n_string_no_quotes_with_bad_escape";
    // n_string_single_doublequote
    EXPECT_FALSE(zjson_accepts(std::string(1, '"'))) << "Should reject: n_string_single_doublequote";
    // n_string_single_quote
    EXPECT_FALSE(zjson_accepts(std::string("['single quote']", 16))) << "Should reject: n_string_single_quote";
    // n_string_single_string_no_double_quotes
    EXPECT_FALSE(zjson_accepts(std::string("abc", 3))) << "Should reject: n_string_single_string_no_double_quotes";
    // n_string_start_escape_unclosed
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\", 3))) << "Should reject: n_string_start_escape_unclosed";
    // n_string_unescaped_ctrl_char
    EXPECT_FALSE(zjson_accepts(std::string("[\"a\x00" "a\"]", 7))) << "Should reject: n_string_unescaped_ctrl_char";
    // n_string_unescaped_newline
    EXPECT_FALSE(zjson_accepts(std::string("[\"new\nline\"]", 12))) << "Should reject: n_string_unescaped_newline";
    // n_string_unescaped_tab
    EXPECT_FALSE(zjson_accepts(std::string("[\"\t\"]", 5))) << "Should reject: n_string_unescaped_tab";
    // n_string_unicode_CapitalU
    EXPECT_FALSE(zjson_accepts(std::string("\"\\UA66D\"", 8))) << "Should reject: n_string_unicode_CapitalU";
    // n_string_with_trailing_garbage
    EXPECT_FALSE(zjson_accepts(std::string("\"\"x", 3))) << "Should reject: n_string_with_trailing_garbage";
    // n_structure_100000_opening_arrays
    EXPECT_FALSE(zjson_accepts(repeat_concat(std::string(1, '['), 100000, std::string("", 0)))) << "Should reject: n_structure_100000_opening_arrays";
    // n_structure_U+2060_word_joined
    EXPECT_FALSE(zjson_accepts(std::string("[\xe2\x81\xa0]", 5))) << "Should reject: n_structure_U+2060_word_joined";
    // n_structure_UTF8_BOM_no_data
    EXPECT_FALSE(zjson_accepts(std::string("\xef\xbb\xbf", 3))) << "Should reject: n_structure_UTF8_BOM_no_data";
    // n_structure_angle_bracket_.
    EXPECT_FALSE(zjson_accepts(std::string("<.>", 3))) << "Should reject: n_structure_angle_bracket_.";
    // n_structure_angle_bracket_null
    EXPECT_FALSE(zjson_accepts(std::string("[<null>]", 8))) << "Should reject: n_structure_angle_bracket_null";
    // n_structure_array_trailing_garbage
    EXPECT_FALSE(zjson_accepts(std::string("[1]x", 4))) << "Should reject: n_structure_array_trailing_garbage";
    // n_structure_array_with_extra_array_close
    EXPECT_FALSE(zjson_accepts(std::string("[1]]", 4))) << "Should reject: n_structure_array_with_extra_array_close";
    // n_structure_array_with_unclosed_string
    EXPECT_FALSE(zjson_accepts(std::string("[\"asd]", 6))) << "Should reject: n_structure_array_with_unclosed_string";
    // n_structure_ascii-unicode-identifier
    EXPECT_FALSE(zjson_accepts(std::string("a\xc3\xa5", 3))) << "Should reject: n_structure_ascii-unicode-identifier";
    // n_structure_capitalized_True
    EXPECT_FALSE(zjson_accepts(std::string("[True]", 6))) << "Should reject: n_structure_capitalized_True";
    // n_structure_close_unopened_array
    EXPECT_FALSE(zjson_accepts(std::string("1]", 2))) << "Should reject: n_structure_close_unopened_array";
}

TEST(JSONTestSuite_n, MustReject_6) {
    // n_structure_comma_instead_of_closing_brace
    EXPECT_FALSE(zjson_accepts(std::string("{\"x\": true,", 11))) << "Should reject: n_structure_comma_instead_of_closing_brace";
    // n_structure_double_array
    EXPECT_FALSE(zjson_accepts(std::string("[][]", 4))) << "Should reject: n_structure_double_array";
    // n_structure_end_array
    EXPECT_FALSE(zjson_accepts(std::string(1, ']'))) << "Should reject: n_structure_end_array";
    // n_structure_incomplete_UTF8_BOM
    EXPECT_FALSE(zjson_accepts(std::string("\xef\xbb{}", 4))) << "Should reject: n_structure_incomplete_UTF8_BOM";
    // n_structure_lone-invalid-utf-8
    EXPECT_FALSE(zjson_accepts(std::string(1, '\xe5'))) << "Should reject: n_structure_lone-invalid-utf-8";
    // n_structure_lone-open-bracket
    EXPECT_FALSE(zjson_accepts(std::string(1, '['))) << "Should reject: n_structure_lone-open-bracket";
    // n_structure_no_data
    EXPECT_FALSE(zjson_accepts(std::string("", 0))) << "Should reject: n_structure_no_data";
    // n_structure_null-byte-outside-string
    EXPECT_FALSE(zjson_accepts(std::string("[\x00]", 3))) << "Should reject: n_structure_null-byte-outside-string";
    // n_structure_number_with_trailing_garbage
    EXPECT_FALSE(zjson_accepts(std::string("2@", 2))) << "Should reject: n_structure_number_with_trailing_garbage";
    // n_structure_object_followed_by_closing_object
    EXPECT_FALSE(zjson_accepts(std::string("{}}", 3))) << "Should reject: n_structure_object_followed_by_closing_object";
    // n_structure_object_unclosed_no_value
    EXPECT_FALSE(zjson_accepts(std::string("{\"\":", 4))) << "Should reject: n_structure_object_unclosed_no_value";
    // n_structure_object_with_comment
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\":/*comment*/\"b\"}", 20))) << "Should reject: n_structure_object_with_comment";
    // n_structure_object_with_trailing_garbage
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\": true} \"x\"", 15))) << "Should reject: n_structure_object_with_trailing_garbage";
    // n_structure_open_array_apostrophe
    EXPECT_FALSE(zjson_accepts(std::string("['", 2))) << "Should reject: n_structure_open_array_apostrophe";
    // n_structure_open_array_comma
    EXPECT_FALSE(zjson_accepts(std::string("[,", 2))) << "Should reject: n_structure_open_array_comma";
    // n_structure_open_array_object
    EXPECT_FALSE(zjson_accepts(repeat_concat(std::string("[{\"\":", 5), 50000, std::string(1, '\x0a')))) << "Should reject: n_structure_open_array_object";
    // n_structure_open_array_open_object
    EXPECT_FALSE(zjson_accepts(std::string("[{", 2))) << "Should reject: n_structure_open_array_open_object";
    // n_structure_open_array_open_string
    EXPECT_FALSE(zjson_accepts(std::string("[\"a", 3))) << "Should reject: n_structure_open_array_open_string";
    // n_structure_open_array_string
    EXPECT_FALSE(zjson_accepts(std::string("[\"a\"", 4))) << "Should reject: n_structure_open_array_string";
    // n_structure_open_object
    EXPECT_FALSE(zjson_accepts(std::string(1, '{'))) << "Should reject: n_structure_open_object";
    // n_structure_open_object_close_array
    EXPECT_FALSE(zjson_accepts(std::string("{]", 2))) << "Should reject: n_structure_open_object_close_array";
    // n_structure_open_object_comma
    EXPECT_FALSE(zjson_accepts(std::string("{,", 2))) << "Should reject: n_structure_open_object_comma";
    // n_structure_open_object_open_array
    EXPECT_FALSE(zjson_accepts(std::string("{[", 2))) << "Should reject: n_structure_open_object_open_array";
    // n_structure_open_object_open_string
    EXPECT_FALSE(zjson_accepts(std::string("{\"a", 3))) << "Should reject: n_structure_open_object_open_string";
    // n_structure_open_object_string_with_apostrophes
    EXPECT_FALSE(zjson_accepts(std::string("{'a'", 4))) << "Should reject: n_structure_open_object_string_with_apostrophes";
}

TEST(JSONTestSuite_n, MustReject_7) {
    // n_structure_open_open
    EXPECT_FALSE(zjson_accepts(std::string("[\"\\{[\"\\{[\"\\{[\"\\{", 16))) << "Should reject: n_structure_open_open";
    // n_structure_single_eacute
    EXPECT_FALSE(zjson_accepts(std::string(1, '\xe9'))) << "Should reject: n_structure_single_eacute";
    // n_structure_single_star
    EXPECT_FALSE(zjson_accepts(std::string(1, '*'))) << "Should reject: n_structure_single_star";
    // n_structure_trailing_#
    EXPECT_FALSE(zjson_accepts(std::string("{\"a\":\"b\"}#{}", 12))) << "Should reject: n_structure_trailing_#";
    // n_structure_uescaped_LF_before_string
    EXPECT_FALSE(zjson_accepts(std::string("[\\u000A\"\"]", 10))) << "Should reject: n_structure_uescaped_LF_before_string";
    // n_structure_unclosed_array
    EXPECT_FALSE(zjson_accepts(std::string("[1", 2))) << "Should reject: n_structure_unclosed_array";
    // n_structure_unclosed_array_partial_null
    EXPECT_FALSE(zjson_accepts(std::string("[ false, nul", 12))) << "Should reject: n_structure_unclosed_array_partial_null";
    // n_structure_unclosed_array_unfinished_false
    EXPECT_FALSE(zjson_accepts(std::string("[ true, fals", 12))) << "Should reject: n_structure_unclosed_array_unfinished_false";
    // n_structure_unclosed_array_unfinished_true
    EXPECT_FALSE(zjson_accepts(std::string("[ false, tru", 12))) << "Should reject: n_structure_unclosed_array_unfinished_true";
    // n_structure_unclosed_object
    EXPECT_FALSE(zjson_accepts(std::string("{\"asd\":\"asd\"", 12))) << "Should reject: n_structure_unclosed_object";
    // n_structure_unicode-identifier
    EXPECT_FALSE(zjson_accepts(std::string("\xc3\xa5", 2))) << "Should reject: n_structure_unicode-identifier";
    // n_structure_whitespace_U+2060_word_joiner
    EXPECT_FALSE(zjson_accepts(std::string("[\xe2\x81\xa0]", 5))) << "Should reject: n_structure_whitespace_U+2060_word_joiner";
    // n_structure_whitespace_formfeed
    EXPECT_FALSE(zjson_accepts(std::string("[\x0c]", 3))) << "Should reject: n_structure_whitespace_formfeed";
}

// ============================================================
// i_: Implementation-defined - ZJSON currently ACCEPTS these
// ============================================================
TEST(JSONTestSuite_i, CurrentlyAccepted_0) {
    // i_number_double_huge_neg_exp
    EXPECT_TRUE(zjson_accepts(std::string("[123.456e-789]", 14))) << "Regression: used to accept: i_number_double_huge_neg_exp";
    // i_number_huge_exp
    EXPECT_TRUE(zjson_accepts(std::string("[0.4e00669999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999969999999006]", 137))) << "Regression: used to accept: i_number_huge_exp";
    // i_number_neg_int_huge_exp
    EXPECT_TRUE(zjson_accepts(std::string("[-1e+9999]", 10))) << "Regression: used to accept: i_number_neg_int_huge_exp";
    // i_number_pos_double_huge_exp
    EXPECT_TRUE(zjson_accepts(std::string("[1.5e+9999]", 11))) << "Regression: used to accept: i_number_pos_double_huge_exp";
    // i_number_real_neg_overflow
    EXPECT_TRUE(zjson_accepts(std::string("[-123123e100000]", 16))) << "Regression: used to accept: i_number_real_neg_overflow";
    // i_number_real_pos_overflow
    EXPECT_TRUE(zjson_accepts(std::string("[123123e100000]", 15))) << "Regression: used to accept: i_number_real_pos_overflow";
    // i_number_real_underflow
    EXPECT_TRUE(zjson_accepts(std::string("[123e-10000000]", 15))) << "Regression: used to accept: i_number_real_underflow";
    // i_number_too_big_neg_int
    EXPECT_TRUE(zjson_accepts(std::string("[-123123123123123123123123123123]", 33))) << "Regression: used to accept: i_number_too_big_neg_int";
    // i_number_too_big_pos_int
    EXPECT_TRUE(zjson_accepts(std::string("[100000000000000000000]", 23))) << "Regression: used to accept: i_number_too_big_pos_int";
    // i_number_very_big_negative_int
    EXPECT_TRUE(zjson_accepts(std::string("[-237462374673276894279832749832423479823246327846]", 51))) << "Regression: used to accept: i_number_very_big_negative_int";
    // i_object_key_lone_2nd_surrogate
    EXPECT_TRUE(zjson_accepts(std::string("{\"\\uDFAA\":0}", 12))) << "Regression: used to accept: i_object_key_lone_2nd_surrogate";
    // i_string_1st_surrogate_but_2nd_missing
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uDADA\"]", 10))) << "Regression: used to accept: i_string_1st_surrogate_but_2nd_missing";
    // i_string_1st_valid_surrogate_2nd_invalid
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uD888\\u1234\"]", 16))) << "Regression: used to accept: i_string_1st_valid_surrogate_2nd_invalid";
    // i_string_UTF-8_invalid_sequence
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xe6\x97\xa5\xd1\x88\xfa\"]", 10))) << "Regression: used to accept: i_string_UTF-8_invalid_sequence";
    // i_string_UTF8_surrogate_U+D800
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xed\xa0\x80\"]", 7))) << "Regression: used to accept: i_string_UTF8_surrogate_U+D800";
    // i_string_incomplete_surrogate_and_escape_valid
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uD800\\n\"]", 12))) << "Regression: used to accept: i_string_incomplete_surrogate_and_escape_valid";
    // i_string_incomplete_surrogate_pair
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uDd1ea\"]", 11))) << "Regression: used to accept: i_string_incomplete_surrogate_pair";
    // i_string_incomplete_surrogates_escape_valid
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uD800\\uD800\\n\"]", 18))) << "Regression: used to accept: i_string_incomplete_surrogates_escape_valid";
    // i_string_invalid_lonely_surrogate
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\ud800\"]", 10))) << "Regression: used to accept: i_string_invalid_lonely_surrogate";
    // i_string_invalid_surrogate
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\ud800abc\"]", 13))) << "Regression: used to accept: i_string_invalid_surrogate";
    // i_string_invalid_utf-8
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xff\"]", 5))) << "Regression: used to accept: i_string_invalid_utf-8";
    // i_string_inverted_surrogates_U+1D11E
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uDd1e\\uD834\"]", 16))) << "Regression: used to accept: i_string_inverted_surrogates_U+1D11E";
    // i_string_iso_latin_1
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xe9\"]", 5))) << "Regression: used to accept: i_string_iso_latin_1";
    // i_string_lone_second_surrogate
    EXPECT_TRUE(zjson_accepts(std::string("[\"\\uDFAA\"]", 10))) << "Regression: used to accept: i_string_lone_second_surrogate";
    // i_string_lone_utf8_continuation_byte
    EXPECT_TRUE(zjson_accepts(std::string("[\"\x81\"]", 5))) << "Regression: used to accept: i_string_lone_utf8_continuation_byte";
}

TEST(JSONTestSuite_i, CurrentlyAccepted_1) {
    // i_string_not_in_unicode_range
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xf4\xbf\xbf\xbf\"]", 8))) << "Regression: used to accept: i_string_not_in_unicode_range";
    // i_string_overlong_sequence_2_bytes
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xc0\xaf\"]", 6))) << "Regression: used to accept: i_string_overlong_sequence_2_bytes";
    // i_string_overlong_sequence_6_bytes
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xfc\x83\xbf\xbf\xbf\xbf\"]", 10))) << "Regression: used to accept: i_string_overlong_sequence_6_bytes";
    // i_string_overlong_sequence_6_bytes_null
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xfc\x80\x80\x80\x80\x80\"]", 10))) << "Regression: used to accept: i_string_overlong_sequence_6_bytes_null";
    // i_string_truncated-utf-8
    EXPECT_TRUE(zjson_accepts(std::string("[\"\xe0\xff\"]", 6))) << "Regression: used to accept: i_string_truncated-utf-8";
}

// ============================================================
// i_: Implementation-defined - ZJSON currently REJECTS these
// ============================================================
TEST(JSONTestSuite_i, CurrentlyRejected) {
    // i_string_UTF-16LE_with_BOM
    EXPECT_FALSE(zjson_accepts(std::string("\xff\xfe[\x00\"\x00\xe9\x00\"\x00]\x00", 12))) << "Regression: used to reject: i_string_UTF-16LE_with_BOM";
    // i_string_utf16BE_no_BOM
    EXPECT_FALSE(zjson_accepts(std::string("\x00[\x00\"\x00\xe9\x00\"\x00]", 10))) << "Regression: used to reject: i_string_utf16BE_no_BOM";
    // i_string_utf16LE_no_BOM
    EXPECT_FALSE(zjson_accepts(std::string("[\x00\"\x00\xe9\x00\"\x00]\x00", 10))) << "Regression: used to reject: i_string_utf16LE_no_BOM";
    // i_structure_500_nested_arrays
    EXPECT_FALSE(zjson_accepts(std::string("[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]", 1000))) << "Regression: used to reject: i_structure_500_nested_arrays";
    // i_structure_UTF-8_BOM_empty_object
    EXPECT_FALSE(zjson_accepts(std::string("\xef\xbb\xbf{}", 5))) << "Regression: used to reject: i_structure_UTF-8_BOM_empty_object";
}


// ============================================================
// Extension mode: comments must be accepted (not strict RFC)
// ============================================================
TEST(JSONTestSuite, extension_mode_comments_accepted) {
    std::string err;

    // ParseJson (extension mode) must accept comments
    auto ext_accept = [&](const std::string& s) {
        Json j = Json::ParseJson(s, err);
        return !j.isError();
    };

    EXPECT_TRUE(ext_accept("{\"a\":/*comment*/\"b\"}"));
    EXPECT_TRUE(ext_accept("{\"a\":\"b\"}/**/"));
    EXPECT_TRUE(ext_accept("[1]//tail\n"));
    EXPECT_TRUE(ext_accept("/**/42"));

    // Strict mode must reject comments
    EXPECT_FALSE(zjson_accepts("{\"a\":/*comment*/\"b\"}"));
    EXPECT_FALSE(zjson_accepts("{\"a\":\"b\"}/**/"));
    EXPECT_FALSE(zjson_accepts("{\"a\":\"b\"}//"));
}

// ============================================================
// UTF-8 validation mode (ParseJsonStrictUtf8)
// ============================================================
TEST(JSONTestSuite, utf8_validation_rejects_invalid_bytes) {
    std::string err;

    // Valid UTF-8 should pass
    Json j1 = Json::ParseJsonStrictUtf8("[\"abc\"]", err);
    EXPECT_FALSE(j1.isError()) << err;

    Json j2 = Json::ParseJsonStrictUtf8("[\"\xc3\xa9\"]", err);  // U+00E9
    EXPECT_FALSE(j2.isError()) << err;

    Json j3 = Json::ParseJsonStrictUtf8("[\"\xe4\xbd\xa0\xe5\xa5\xbd\"]", err);  // U+4F60 U+597D
    EXPECT_FALSE(j3.isError()) << err;

    Json j4 = Json::ParseJsonStrictUtf8("[\"\xf0\x9d\x84\x9e\"]", err);  // U+1D11E
    EXPECT_FALSE(j4.isError()) << err;

    // Invalid: lone continuation byte
    Json j5 = Json::ParseJsonStrictUtf8(std::string("[\"a\x80\"]"), err);
    EXPECT_TRUE(j5.isError());
    EXPECT_NE(err.find("UTF-8"), std::string::npos);

    // Invalid: overlong 2-byte encoding of ASCII
    Json j6 = Json::ParseJsonStrictUtf8(std::string("[\"a\xc0\xaf\"]"), err);
    EXPECT_TRUE(j6.isError());

    // Invalid: truncated 3-byte sequence
    Json j7 = Json::ParseJsonStrictUtf8(std::string("[\"a\xe0\x80\"]"), err);
    EXPECT_TRUE(j7.isError());

    // Invalid: surrogate half U+D800
    Json j8 = Json::ParseJsonStrictUtf8(std::string("[\"a\xed\xa0\x80\"]"), err);
    EXPECT_TRUE(j8.isError());

    // Invalid: above U+10FFFF  (F4 90 80 80)
    Json j9 = Json::ParseJsonStrictUtf8(std::string("[\"a\xf4\x90\x80\x80\"]"), err);
    EXPECT_TRUE(j9.isError());

    // Invalid: 5-byte sequence (never valid UTF-8)
    Json j10 = Json::ParseJsonStrictUtf8(std::string("[\"a\xf8\x80\x80\x80\x80\"]"), err);
    EXPECT_TRUE(j10.isError());
}

TEST(JSONTestSuite, utf8_validation_accepts_valid_in_keys) {
    std::string err;
    // UTF-8 in key names
    Json j = Json::ParseJsonStrictUtf8("{\"cl\xc3\xa9\":\"val\"}", err);
    EXPECT_FALSE(j.isError()) << err;
}

// ============================================================
// Deep nesting (PDA must handle without stack overflow)
// ============================================================
TEST(JSONTestSuite, deep_nesting_pda_safety) {
    // 100 levels should succeed (max_depth)
    {
        std::string deep;
        for (int i = 0; i < 100; ++i) deep.push_back('[');
        deep += "null";
        for (int i = 0; i < 100; ++i) deep.push_back(']');

        std::string err;
        Json j = Json::ParseJsonStrict(deep, err);
        EXPECT_FALSE(j.isError()) << err;
    }

    // 102 levels should fail (> max_depth)
    {
        std::string deep;
        for (int i = 0; i < 102; ++i) deep.push_back('[');
        deep += "null";
        for (int i = 0; i < 102; ++i) deep.push_back(']');

        std::string err;
        Json j = Json::ParseJsonStrict(deep, err);
        EXPECT_TRUE(j.isError());
    }

    // Even very deep failing nesting must not crash (PDA uses heap stack)
    {
        std::string deep;
        for (int i = 0; i < 10000; ++i) deep.push_back('[');
        std::string err;
        Json j = Json::ParseJsonStrict(deep, err);
        EXPECT_TRUE(j.isError());
    }
}

// ============================================================
// Stress: parse -> copy -> move -> toString -> re-parse in tight loop
// ============================================================
TEST(JSONTestSuite, stress_round_trip) {
    const std::string sample =
        "{\"arr\":[1,2,3],\"obj\":{\"key\":\"value\",\"n\":-0.5e+3},\"t\":true,\"f\":false,\"nil\":null}";

    for (int i = 0; i < 3000; ++i) {
        std::string err;
        Json parsed = Json::ParseJsonStrict(sample, err);
        ASSERT_FALSE(parsed.isError()) << err;

        Json copied = parsed;
        Json moved = std::move(copied);

        std::string out = moved.toString();
        Json reparsed = Json::ParseJsonStrict(out, err);
        ASSERT_FALSE(reparsed.isError()) << err;
        ASSERT_EQ(reparsed["arr"][1].toInt(), 2);
    }
}
